name: my-symfony-app
type: "php:8.0"
relationships:
  database: "mysql:mysql"
variables:
  APP_ENV: 'prod'
  APP_DEBUG: '0'
hooks:
  build: |
    set -e
    composer install --prefer-dist --no-interaction --no-progress --no-suggest
    bin/console doctrine:schema:update --force
    bin/console cache:clear
  deploy: |
    set -e
    bin/console cache:clear


# L'espace disque configurés
disk: 2048

# Les dossiers qui doivent rester accessibles en écriture
mounts:
    "/var/cache": "shared:files/cache"
    "/var/log": "shared:files/log"
    "/var/sessions": "shared:files/sessions"

# La configuration web
web:
    locations:
        "/":
            # Dossier public
            root: "public"
            # Le contrôleur frontal (qui doit recevoir toutes les requêtes)
            passthru: "/index.php"

